development:
  adapter: postgresql
  encoding: unicode
  username: tmb
  password:
  database: food-pantry_development

test: &test
  adapter: postgresql
  encoding: unicode
  username: tmb
  password:
  database: food-pantry_test

production:

  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  database: food-pantry_production
  min_messages: warning

cucumber:
  <<: *test
